=== Meta-Platform/meta-platform-applications-repository/Apps.Module/Tools.layer/APIDesigner.group/api-designer.desktopapp/metadata/startup-params-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "port": { "type": "string", "pattern": "^[0-9]+$" },
    "serverName": { "type": "string" },
    "serverManagerUrl": { "type": "string", "format": "uri" },
    "windowUrl": { "type": "string", "format": "uri" },
    "apisDirPath": { "type": "string" },
    "RT_ENV_GENERATED_DIR_NAME": { "type": "string" }
  },
  "required": ["port", "serverName", "serverManagerUrl", "windowUrl", "apisDirPath", "RT_ENV_GENERATED_DIR_NAME"]
}

=== Meta-Platform/meta-platform-applications-repository/Apps.Module/Tools.layer/APIDesigner.group/api-designer.desktopapp/metadata/startup-params.json
{
    "port":"8083",
    "serverName":"APIDesignerDesktopInstance",
    "serverManagerUrl": "http://localhost:8083/server-manager/status",
    "windowUrl": "http://localhost:8083/",
    "apisDirPath":"/home/kadisk/virtual-desk-state/local-app-data/api-designer-apis",
    "RT_ENV_GENERATED_DIR_NAME":".generated_data"
}
